CREATE TABLE football_data.stats_matches
(
    ID VARCHAR(10) NOT NULL,
    BALL_POSSESSION INTEGER NOT NULL,
    GOAL_ATTEMPTS INTEGER NOT NULL,
    SHOTS_ON_GOAL INTEGER DEFAULT 0,
    SHOTS_OFF_GOAL INTEGER DEFAULT 0,
    BLOCKED_SHOTS INTEGER DEFAULT 0,
    FREE_KICKS INTEGER DEFAULT 0,
    CORNERS INTEGER NOT NULL,
    OFFSIDES INTEGER DEFAULT 0,
    THROW_IN INTEGER DEFAULT 0,
    GOALKEEPER_SAVES INTEGER DEFAULT 0,
    FOULS INTEGER DEFAULT 0,
    YELLOW_CARDS INTEGER DEFAULT 0,
    RED_CARDS INTEGER DEFAULT 0,
    COMPLETED_PASSES INTEGER DEFAULT 0,
    TACKLES INTEGER DEFAULT 0,
    ATTACKS INTEGER DEFAULT 0,
    DANGEROUS_ATTACKS INTEGER DEFAULT 0
)