INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (1,"Saint-Etienne", "saint-etienne-as-weather");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (2,"Lille", "grand-stade-lille-mtropole-lille-weather");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (3,"Angers", "angers-weather/pays-de-la-loire");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (4,"Lorient", "lorient-fc-weather");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (5,"Monaco", "condamine-weather");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (6,"Nantes", "nantes-weather/pays-de-la-loire");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (7,"Niza", "nice-weather/provence-alpes-cote-dazur");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (8,"Montpellier", "stade-de-la-mosson-montpellier-weather");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (9,"Lens", "lens-weather");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (10,"Clermont", "clermont-ferrand-weather/auvergne");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (11,"Marsella", "marseille-weather/provence-alpes-cote-dazur");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (12,"Brest", "keroriou-weather/bretagne");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (13,"Reims", "reims-weather/champagne-ardenne");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (14,"Stade Rennais", "rennes-weather");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (15,"Troyes", "troyes-weather/champagne-ardenne");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (16,"Girondins", "port-de-bassens-weather/aquitaine");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (17,"Lyon", "olympique-lyonnais-weather");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (18,"PSG", "paris-saint-germain-weather");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (19,"Estrasburgo", "strasburg-weather/alsace");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (20,"Metz", "divodurum-weather/lorraine");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (21,"Granada", "granada-weather/andalucia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (22,"Osasuna", "san-juan-weather/navarra");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (23,"Real Madrid", "casas-de-la-prosperidad-weather/madrid");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (24,"Villarreal", "villareal-weather/comunidad-valenciana");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (25,"Sevilla", "seville-weather/andalucia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (26,"Athletic Club", "bilbao-weather/pais-vasco");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (27,"Levante", "valenza-weather/comunidad-valenciana");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (28,"Getafe", "getafe-weather/madrid");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (29,"Barcelona", "barcelona-weather/catalonia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (30,"Valencia", "valenza-weather/comunidad-valenciana");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (31,"Real Betis", "seville-weather/andalucia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (32,"Real Sociedad", "donostia-san-sebastian-weather/pais-vasco");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (33,"Mallorca", "majorca-weather/islas-baleares");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (34,"Alaves", "ali-weather/pais-vasco");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (35,"Atletico de Madrid", "coslada-weather/madrid");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (36,"Elche", "elche-weather/comunidad-valenciana");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (37,"Rayo Vallecano", "puente-de-vallecas-weather/madrid");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (38,"Celta de Vigo", "vigo-weather/galicia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (39,"Cadiz", "cadiz-weather/andalucia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (40,"Leganes", "leganes-weather/madrid");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (41,"Eibar", "eibar-weather/pais-vasco");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (42,"Huesca", "huesca-weather/aragon");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (43,"Real Valladolid", "valladolid-weather/castilla-y-leon");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (44,"West Brom", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (45,"Tottenham", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (46,"Arsenal", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (47,"Swansea", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (48,"Everton", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (49,"Chelsea", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (50,"Aston Villa", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (51,"Bournemouth", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (52,"Norwich", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (53,"Manchester City", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (54,"Sunderland", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (55,"Crystal Palace", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (56,"Watford", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (57,"Leicester", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (58,"Newcastle", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (59,"Liverpool", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (60,"Manchester Utd", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (61,"Southampton", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (62,"Stoke", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (63,"West Ham", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (64,"Huddersfield", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (65,"Wolves", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (66,"Brighton", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (67,"Burnley", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (68,"Cardiff", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (69,"Fulham", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (70,"Hannover", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (71,"Hertha BSC", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (72,"Bayern Munich", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (73,"Hoffenheim", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (74,"Werder Bremen", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (75,"Eintracht Frankfurt", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (76,"Colonia", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (77,"Wolfsburgo", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (78,"Mainz", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (79,"Augsburgo", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (80,"Hamburgo", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (81,"Paderborn", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (82,"Schalke", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (83,"Stuttgart", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (84,"Friburgo", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (85,"Borussia M\'gladbach", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (86,"Borussia Dortmund", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (87,"Bayer Leverkusen", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (88,"Darmstadt", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (89,"Nuremberg", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (90,"RB Leipzig", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (91,"Fortuna Dusseldorf", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (92,"Torino", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (93,"Palermo", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (94,"Atalanta", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (95,"Udinese", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (96,"Genoa", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (97,"Roma", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (98,"Sassuolo", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (99,"AC Milan", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (100,"Chievo", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (101,"Cesena", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (102,"Verona", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (103,"Parma", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (104,"Cagliari", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (105,"Fiorentina", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (106,"Inter", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (107,"Lazio", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (108,"Napoles", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (109,"Sampdoria", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (110,"Juventus", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (111,"Empoli", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (112,"Carpi", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (113,"Frosinone", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (114,"Bolonia", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (115,"Spal", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (116,"Benevento", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (117,"Crotone", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (118, "Amiens", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (119,"Dijon", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (120,"Nimes", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (121,"SM Caen", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (122,"EA Guingamp", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (123,"Almeria", "almeria-weather/andalucia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (124,"Malaga", "malaga-weather/andalucia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (125,"Cordoba", "cordoba-weather/andalucia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (126,"Deportivo de La Coruna", "la-corogne-weather/galicia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (127,"Hull", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (128,"Sheffield Utd", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (129,"Ingolstadt", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (130,"Toulouse", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (131,"Union Berlin", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (132,"Lecce", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (133,"Sporting de Gijon", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (134,"Leeds Utd", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (135,"Brentford", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (136,"Pescara", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (137,"Arminia Bielefeld", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (138,"QPR", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (139,"Las Palmas", "majorca-weather/islas-baleares");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (140,"Girona", "girona-weather/catalonia");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (141,"Brescia", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (142,"Spezia", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (143,"Salernitana", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (144,"Venezia", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (145,"Bochum", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (146,"Greuther Furth", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (147,"Middlesbrough", "");
INSERT INTO football_data.stadiums (ID, URL, SEASON, LEAGUE) VALUES (148,"Espanyol", "cornella-weather/catalonia");