INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (1,"Saint-Etienne", "saint-etienne-as-weather/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (2,"Lille", "grand-stade-lille-mtropole-lille-weather/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (3,"Angers", "angers-weather/pays-de-la-loire/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (4,"Lorient", "lorient-fc-weather/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (5,"Monaco", "condamine-weather/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (6,"Nantes", "nantes-weather/pays-de-la-loire/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (7,"Niza", "nice-weather/provence-alpes-cote-dazur/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (8,"Montpellier", "stade-de-la-mosson-montpellier-weather/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (9,"Lens", "lens-weather/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (10,"Clermont", "clermont-ferrand-weather/auvergne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (11,"Marsella", "marseille-weather/provence-alpes-cote-dazur/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (12,"Brest", "keroriou-weather/bretagne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (13,"Reims", "reims-weather/champagne-ardenne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (14,"Stade Rennais", "rennes-weather/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (15,"Troyes", "troyes-weather/champagne-ardenne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (16,"Girondins", "port-de-bassens-weather/aquitaine/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (17,"Lyon", "olympique-lyonnais-weather/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (18,"PSG", "paris-saint-germain-weather/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (19,"Estrasburgo", "strasburg-weather/alsace/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (20,"Metz", "divodurum-weather/lorraine/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (21,"Granada", "granada-weather/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (22,"Osasuna", "san-juan-weather/navarra/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (23,"Real Madrid", "casas-de-la-prosperidad-weather/madrid/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (24,"Villarreal", "villareal-weather/comunidad-valenciana/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (25,"Sevilla", "seville-weather/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (26,"Athletic Club", "bilbao-weather/pais-vasco/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (27,"Levante", "valenza-weather/comunidad-valenciana/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (28,"Getafe", "getafe-weather/madrid/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (29,"Barcelona", "barcelona-weather/catalonia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (30,"Valencia", "valenza-weather/comunidad-valenciana/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (31,"Real Betis", "seville-weather/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (32,"Real Sociedad", "donostia-san-sebastian-weather/pais-vasco/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (33,"Mallorca", "majorca-weather/islas-baleares/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (34,"Alaves", "ali-weather/pais-vasco/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (35,"Atletico de Madrid", "coslada-weather/madrid/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (36,"Elche", "elche-weather/comunidad-valenciana/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (37,"Rayo Vallecano", "puente-de-vallecas-weather/madrid/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (38,"Celta de Vigo", "vigo-weather/galicia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (39,"Cadiz", "cadiz-weather/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (40,"Leganes", "leganes-weather/madrid/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (41,"Eibar", "eibar-weather/pais-vasco/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (42,"Huesca", "huesca-weather/aragon/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (43,"Real Valladolid", "valladolid-weather/castilla-y-leon/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (44,"West Brom", "mayers-green-weather/west-midlands/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (45,"Tottenham", "edmonton-weather/enfield-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (46,"Arsenal", "pentonville-weather/islington-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (47,"Swansea", "st-thomas-weather/swansea/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (48,"Everton", "vauxhall-weather/merseyside/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (49,"Chelsea", "chelsea-weather/kingston-upon-thames-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (50,"Aston Villa", "aston-weather/west-midlands/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (51,"Bournemouth", "bournemouth-weather/dorset/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (52,"Norwich", "norwich-weather/norfolk/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (53,"Manchester City", "etihad-stadium-manchester-weather/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (54,"Sunderland", "bishopwearmouth-weather/tyne-and-wear/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (55,"Crystal Palace", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (56,"Watford", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (57,"Leicester", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (58,"Newcastle", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (59,"Liverpool", "vauxhall-weather/merseyside/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (60,"Manchester Utd", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (61,"Southampton", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (62,"Stoke", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (63,"West Ham", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (64,"Huddersfield", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (65,"Wolves", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (66,"Brighton", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (67,"Burnley", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (68,"Cardiff", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (69,"Fulham", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (70,"Hannover", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (71,"Hertha BSC", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (72,"Bayern Munich", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (73,"Hoffenheim", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (74,"Werder Bremen", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (75,"Eintracht Frankfurt", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (76,"Colonia", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (77,"Wolfsburgo", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (78,"Mainz", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (79,"Augsburgo", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (80,"Hamburgo", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (81,"Paderborn", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (82,"Schalke", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (83,"Stuttgart", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (84,"Friburgo", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (85,"Borussia M\'gladbach", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (86,"Borussia Dortmund", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (87,"Bayer Leverkusen", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (88,"Darmstadt", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (89,"Nuremberg", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (90,"RB Leipzig", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (91,"Fortuna Dusseldorf", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (92,"Torino", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (93,"Palermo", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (94,"Atalanta", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (95,"Udinese", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (96,"Genoa", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (97,"Roma", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (98,"Sassuolo", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (99,"AC Milan", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (100,"Chievo", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (101,"Cesena", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (102,"Verona", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (103,"Parma", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (104,"Cagliari", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (105,"Fiorentina", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (106,"Inter", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (107,"Lazio", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (108,"Napoles", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (109,"Sampdoria", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (110,"Juventus", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (111,"Empoli", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (112,"Carpi", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (113,"Frosinone", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (114,"Bolonia", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (115,"Spal", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (116,"Benevento", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (117,"Crotone", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (118, "Amiens", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (119,"Dijon", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (120,"Nimes", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (121,"SM Caen", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (122,"EA Guingamp", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (123,"Almeria", "almeria-weather/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (124,"Malaga", "malaga-weather/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (125,"Cordoba", "cordoba-weather/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (126,"Deportivo de La Coruna", "la-corogne-weather/galicia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (127,"Hull", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (128,"Sheffield Utd", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (129,"Ingolstadt", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (130,"Toulouse", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (131,"Union Berlin", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (132,"Lecce", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (133,"Sporting de Gijon", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (134,"Leeds Utd", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (135,"Brentford", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (136,"Pescara", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (137,"Arminia Bielefeld", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (138,"QPR", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (139,"Las Palmas", "majorca-weather/islas-baleares/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (140,"Girona", "girona-weather/catalonia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (141,"Brescia", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (142,"Spezia", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (143,"Salernitana", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (144,"Venezia", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (145,"Bochum", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (146,"Greuther Furth", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (147,"Middlesbrough", "");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (148,"Espanyol", "cornella-weather/catalonia/es.aspx");