INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (1,"Saint-Etienne", "saint-etienne-weather-history/rhone-alpes/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (2,"Lille", "lille-weather-history/nord-pas-de-calais/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (3,"Angers", "angers-weather-history/pays-de-la-loire/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (4,"Lorient", "lorient-weather-history/bretagne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (5,"Monaco", "monaco-weather-history/mc.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (6,"Nantes", "nantes-weather-history/pays-de-la-loire/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (7,"Niza", "nice-weather-history/provence-alpes-cote-dazur/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (8,"Montpellier", "montpellier-weather-history/languedoc-roussillon/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (9,"Lens", "lens-weather-history/nord-pas-de-calais/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (10,"Clermont", "clermont-ferrand-weather-history/auvergne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (11,"Marsella", "marseille-weather-history/provence-alpes-cote-dazur/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (12,"Brest", "keroriou-weather-history/bretagne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (13,"Reims", "reims-weather-history/champagne-ardenne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (14,"Stade Rennais", "rennes-weather-history/bretagne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (15,"Troyes", "troyes-weather-history/champagne-ardenne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (16,"Girondins", "port-de-bassens-weather-history/aquitaine/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (17,"Lyon", "lyon-weather-history/rhone-alpes/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (18,"PSG", "paris-weather-history/ile-de-france/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (19,"Estrasburgo", "strasburg-weather-history/alsace/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (20,"Metz", "divodurum-weather-history/lorraine/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (21,"Granada", "granada-weather-history/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (22,"Osasuna", "san-juan-weather-history/navarra/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (23,"Real Madrid", "casas-de-la-prosperidad-weather-history/madrid/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (24,"Villarreal", "villareal-weather-history/comunidad-valenciana/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (25,"Sevilla", "seville-weather-history/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (26,"Athletic Club", "bilbao-weather-history/pais-vasco/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (27,"Levante", "valenza-weather-history/comunidad-valenciana/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (28,"Getafe", "getafe-weather-history/madrid/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (29,"Barcelona", "barcelona-weather-history/catalonia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (30,"Valencia", "valenza-weather-history/comunidad-valenciana/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (31,"Real Betis", "seville-weather-history/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (32,"Real Sociedad", "donostia-san-sebastian-weather-history/pais-vasco/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (33,"Mallorca", "majorca-weather-history/islas-baleares/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (34,"Alaves", "ali-weather-history/pais-vasco/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (35,"Atletico de Madrid", "coslada-weather-history/madrid/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (36,"Elche", "elche-weather-history/comunidad-valenciana/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (37,"Rayo Vallecano", "puente-de-vallecas-weather-history/madrid/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (38,"Celta de Vigo", "vigo-weather-history/galicia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (39,"Cadiz", "cadiz-weather-history/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (40,"Leganes", "leganes-weather-history/madrid/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (41,"Eibar", "eibar-weather-history/pais-vasco/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (42,"Huesca", "huesca-weather-history/aragon/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (43,"Real Valladolid", "valladolid-weather-history/castilla-y-leon/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (44,"West Brom", "mayers-green-weather-history/west-midlands/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (45,"Tottenham", "edmonton-weather-history/enfield-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (46,"Arsenal", "pentonville-weather-history/islington-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (47,"Swansea", "st-thomas-weather-history/swansea/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (48,"Everton", "vauxhall-weather-history/merseyside/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (49,"Chelsea", "chelsea-weather-history/kingston-upon-thames-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (50,"Aston Villa", "aston-weather-history/west-midlands/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (51,"Bournemouth", "bournemouth-weather-history/dorset/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (52,"Norwich", "norwich-weather-history/norfolk/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (53,"Manchester City", "manchester-weather-history/greater-manchester/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (54,"Sunderland", "bishopwearmouth-weather-history/tyne-and-wear/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (55,"Crystal Palace", "wandle-park-weather-history/croydon-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (56,"Watford", "west-watford-weather-history/hertfordshire/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (57,"Leicester", "leicester-weather-history/leicestershire/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (58,"Newcastle", "somers-town-weather-history/camden-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (59,"Liverpool", "vauxhall-weather-history/merseyside/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (60,"Manchester Utd", "gorse-hill-weather-history/greater-manchester/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (61,"Southampton", "ocean-village-weather-history/hampshire/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (62,"Stoke", "stoke-upon-trent-weather-history/staffordshire/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (63,"West Ham", "mill-meads-weather-history/newham-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (64,"Huddersfield", "huddersfield-weather-history/west-yorkshire/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (65,"Wolves", "wolverhampton-weather-history/west-midlands/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (66,"Brighton", "kemp-town-weather-history/east-sussex/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (67,"Burnley", "burnley-weather-history/lancashire/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (68,"Cardiff", "cardiff-weather-history/cardiff/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (69,"Fulham", "fulham-weather-history/hammersmith-fulham-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (70,"Hannover", "hanover-weather-history/niedersachsen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (71,"Hertha BSC", "holzgerlingen-weather-history/baden-wurttemberg/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (72,"Bayern Munich", "munich-weather-history/bayern/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (73,"Hoffenheim", "hoffenheim-weather-history/baden-wurttemberg/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (74,"Werder Bremen", "bremen-weather-history/bremen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (75,"Eintracht Frankfurt", "frankford-on-main-weather-history/hessen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (76,"Colonia", "cologne-weather-history/nordrhein-westfalen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (77,"Wolfsburgo", "wolfsburg-weather-history/niedersachsen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (78,"Mainz", "mainz-weather-history/rheinland-pfalz/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (79,"Augsburgo", "augsburg-weather-history/bayern/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (80,"Hamburgo", "hamburg-weather-history/hamburg/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (81,"Paderborn", "paderborn-weather-history/nordrhein-westfalen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (82,"Schalke", "bulmke-weather-history/nordrhein-westfalen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (83,"Stuttgart", "stuttgart-weather-history/baden-wurttemberg/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (84,"Friburgo", "freiburg-weather-history/baden-wurttemberg/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (85,"Borussia Mgladbach", "monchengladbach-weather-history/nordrhein-westfalen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (86,"Borussia Dortmund", "dortmund-weather-history/nordrhein-westfalen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (87,"Bayer Leverkusen", "leverkusen-weather-history/nordrhein-westfalen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (88,"Darmstadt", "darmstadt-weather-history/hessen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (89,"Nuremberg", "nuremberg-weather-history/bayern/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (90,"RB Leipzig", "leipzig-weather-history/sachsen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (91,"Fortuna Dusseldorf", "dusseldorf-weather-history/nordrhein-westfalen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (92,"Torino", "turin-weather-history/piemonte/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (93,"Palermo", "palermo-weather-history/sicilia/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (94,"Atalanta", "valtesse-weather-history/lombardia/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (95,"Udinese", "udine-weather-history/friuli-venezia-giulia/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (96,"Genoa", "genes-weather-history/liguria/it.aspx         ");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (97,"Roma", "rome-weather-history/lazio/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (98,"Sassuolo", "reggio-nell-emilia-weather-history/emilia-romagna/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (99,"AC Milan", "milan-weather-history/lombardia/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (100,"Chievo", "castelnuovo-di-verona-weather-history/veneto/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (101,"Cesena", "cesena-weather-history/emilia-romagna/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (102,"Verona", "verona-weather-history/veneto/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (103,"Parma", "parma-weather-history/emilia-romagna/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (104,"Cagliari", "cagliari-weather-history/sardegna/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (105,"Fiorentina", "florence-weather-history/toscana/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (106,"Inter", "milan-weather-history/lombardia/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (107,"Lazio", "rom-weather-history/lazio/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (108,"Napoles", "napoli-weather-history/campania/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (109,"Sampdoria", "genes-weather-history/liguria/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (110,"Juventus", "turin-weather-history/piemonte/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (111,"Empoli", "empoli-weather-history/toscana/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (112,"Carpi", "carpi-weather-history/emilia-romagna/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (113,"Frosinone", "frosinone-weather-history/lazio/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (114,"Bolonia", "bologna-weather-history/emilia-romagna/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (115,"Spal", "borgo-malpasso-weather-history/emilia-romagna/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (116,"Benevento", "benevento-weather-history/campania/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (117,"Crotone", "crotone-weather-history/calabria/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (118, "Amiens", "amiens-weather-history/picardie/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (119,"Dijon", "chalons-weather-history/bourgogne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (120,"Nimes", "nimes-weather-history/languedoc-roussillon/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (121,"SM Caen", "caen-weather-history/basse-normandie/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (122,"EA Guingamp", "guingamp-weather-history/bretagne/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (123,"Almeria", "almeria-weather-history/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (124,"Malaga", "malaga-weather-history/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (125,"Cordoba", "cordoba-weather-history/andalucia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (126,"Deportivo de La Coruna", "la-corogne-weather-history/galicia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (127,"Hull", "victoria-dock-village-weather-history/east-riding-of-yorkshire/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (128,"Sheffield Utd", "sheffield-weather-history/south-yorkshire/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (129,"Ingolstadt", "ingolstadt-weather-history/bayern/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (130,"Toulouse", "toulouse-weather-history/midi-pyrenees/fr.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (131,"Union Berlin", "berlin-weather-history/berlin/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (132,"Lecce", "san-ligorio-weather-history/puglia/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (133,"Sporting de Gijon", "gijon-weather-history/asturias/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (134,"Leeds Utd", "pottery-field-weather-history/west-yorkshire/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (135,"Brentford", "brentford-end-weather-history/hounslow-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (136,"Pescara", "pescara-weather-history/abruzzi/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (137,"Arminia Bielefeld", "sudbrack-weather-history/nordrhein-westfalen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (138,"QPR", "brook-green-weather-history/hammersmith-fulham-greater-london/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (139,"Las Palmas", "majorca-weather-history/islas-baleares/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (140,"Girona", "girona-weather-history/catalonia/es.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (141,"Brescia", "brescia-weather-history/lombardia/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (142,"Spezia", "la-spezia-weather-history/liguria/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (143,"Salernitana", "salerno-weather-history/campania/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (144,"Venezia", "la-giudecca-weather-history/veneto/it.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (145,"Bochum", "bochum-weather-history/nordrhein-westfalen/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (146,"Greuther Furth", "furth-weather-history/bayern/de.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (147,"Middlesbrough", "port-clarence-weather-history/county-durham/gb.aspx");
INSERT INTO football_data.stadiums (ID, TEAM, PLACE_WEATHER) VALUES (148,"Espanyol", "cornella-weather-history/catalonia/es.aspx");